const PDFDocument = require("pdfkit");
const Scan = require("../models/Scan");

const getAllReports = async (req, res) => {
  try {
    const reports = await Scan.find({
      userId: req.userId,
    }).sort({ createdAt: -1 });

    res.status(200).json({
      success: true,
      count: reports.length,
      reports,
    });
  } catch (error) {
    console.error("Reports error:", error);

    res.status(500).json({
      success: false,
      message: "Unable to fetch reports.",
    });
  }
};

// Generate PDF report for a single scan
const downloadScanReport = async (req, res) => {
  try {
    const { scanId } = req.params;

    const scan = await Scan.findOne({
      _id: scanId,
      userId: req.userId,
    });

    if (!scan) {
      return res.status(404).json({
        success: false,
        message: "Scan report not found.",
      });
    }

    const doc = new PDFDocument({
      size: "A4",
      margin: 50,
    });

    const fileName = `ScamShield_Report_${scan._id}.pdf`;

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
      "Content-Disposition",
      `attachment; filename="${fileName}"`
    );

    doc.pipe(res);

    // =========================================
    // HEADER
    // =========================================

    doc
      .fontSize(22)
      .font("Helvetica-Bold")
      .text("ScamShield AI Security Report", {
        align: "center",
      });

    doc
      .moveDown(0.5)
      .fontSize(10)
      .font("Helvetica")
      .fillColor("#666666")
      .text(
        "AI-powered phishing and scam detection",
        { align: "center" }
      );

    doc.moveDown(1.5);

    // =========================================
    // SCAN INFORMATION
    // =========================================

    doc
      .fillColor("#000000")
      .fontSize(15)
      .font("Helvetica-Bold")
      .text("Scan Information");

    doc.moveDown(0.5);

    doc
      .fontSize(10)
      .font("Helvetica")
      .text(`Report ID: ${scan._id}`)
      .text(`Scan Type: ${scan.type}`)
      .text(`Target: ${scan.target}`)
      .text(`Date: ${new Date(scan.createdAt).toLocaleString()}`);

    doc.moveDown(1);

    // =========================================
    // RISK ASSESSMENT
    // =========================================

    doc
      .fontSize(15)
      .font("Helvetica-Bold")
      .text("Risk Assessment");

    doc.moveDown(0.5);

    doc
      .fontSize(10)
      .font("Helvetica")
      .text(`Risk Score: ${scan.score}/100`)
      .text(`Threat Level: ${scan.level}`)
      .text(`Category: ${scan.category}`);

    doc.moveDown(1);

    // =========================================
    // AI / ML ANALYSIS
    // =========================================

    doc
      .fontSize(15)
      .font("Helvetica-Bold")
      .text("AI / ML Analysis");

    doc.moveDown(0.5);

    doc
      .fontSize(10)
      .font("Helvetica")
      .text(
        `Prediction: ${
          scan.prediction || "Not available"
        }`
      )
      .text(
        `ML Confidence: ${
          scan.confidence != null
            ? `${scan.confidence}%`
            : "Not available"
        }`
      );

    // =========================================
    // URL FEATURES
    // =========================================

    if (
      scan.type === "URL" &&
      Array.isArray(scan.features) &&
      scan.features.length > 0
    ) {
      doc.moveDown(1);

      doc
        .fontSize(15)
        .font("Helvetica-Bold")
        .text("URL Feature Analysis");

      doc.moveDown(0.5);

      scan.features.forEach((feature, index) => {
        doc
          .fontSize(9)
          .font("Helvetica")
          .text(
            `Feature ${index + 1}: ${feature}`
          );
      });
    }

    // =========================================
    // DETECTION FINDINGS
    // =========================================

    doc.moveDown(1);

    doc
      .fontSize(15)
      .font("Helvetica-Bold")
      .text("Detection Findings");

    doc.moveDown(0.5);

    if (
      Array.isArray(scan.reasons) &&
      scan.reasons.length > 0
    ) {
      scan.reasons.forEach((reason, index) => {
        doc
          .fontSize(9)
          .font("Helvetica")
          .text(`${index + 1}. ${reason}`);
      });
    } else {
      doc
        .fontSize(9)
        .font("Helvetica")
        .text("No additional findings available.");
    }

    doc.moveDown(1.5);

    // =========================================
    // FOOTER
    // =========================================

    doc
      .fontSize(8)
      .fillColor("#666666")
      .text(
        "Generated by ScamShield AI Security Platform",
        {
          align: "center",
        }
      );

    doc.end();
  } catch (error) {
    console.error("PDF report error:", error);

    if (!res.headersSent) {
      res.status(500).json({
        success: false,
        message: "Unable to generate PDF report.",
      });
    }
  }
};

module.exports = {
  getAllReports,
  downloadScanReport,
};